=== carlonsss/xml-validaci-n-dtd-2/xml dtd 2/Ejercicio 3/aeropuerto.dtd
<!ELEMENT aeropuerto (nombre, fecha, panel)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT panel (vuelo+)>
<!ELEMENT vuelo (diario?, origen, destino, hora_salida, hora_llegada)>
<!ATTLIST vuelo codigo ID #REQUIRED>
<!ATTLIST vuelo estado (C | E | R) "E">
<!ELEMENT diario EMPTY>
<!ELEMENT origen (#PCDATA)>
<!ELEMENT destino (#PCDATA)>
<!ELEMENT hora_salida (#PCDATA)>
<!ELEMENT hora_llegada (#PCDATA)>

=== carlonsss/xml-validaci-n-dtd-2/xml dtd 2/Ejercicio 3/aeropuerto.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
Nombre: Carlos Gil
Curso: [Asir] 
Fecha: [3/4/2025] 
Ejercicio: [Nba] 
-->
-->
<!DOCTYPE aeropuerto SYSTEM "aeropuerto.dtd">
<aeropuerto>
    <nombre>JFK</nombre>
    <panel>
        <vuelo codigo="V22" estado="R">
            <diario />
            <origen>New York</origen>
            <destino>Chicago</destino>
            <hora_salida>9:30</hora_salida>
            <hora_llegada>11:30</hora_llegada>
        </vuelo>
        <vuelo codigo="V23" estado="C">
            <origen>New York</origen>
            <destino>Miami</destino>
            <hora_salida>10:15</hora_salida>
            <hora_llegada>11:15</hora_llegada>
        </vuelo>
    </panel>
    <fecha>20/12/2013</fecha>
</aeropuerto>
